

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest

  kafka:
    image: confluentinc/cp-kafka:latest

  postgres:
    image: postgres:16

  redis:
    image: redis:7

  transaction-gateway:
    build: ./transaction-gateway

  ledger-service:
    build: ./ledger-service

  analytics-worker:
    build: ./analytics-worker
