name: SwiftPay CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup Java
        uses: actions/setup-java@v4.7.0
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Build common-lib first
        run: mvn clean install -pl common-lib -am -DskipTests

      - name: Package all modules
        run: mvn package -DskipTests

      - name: Run Tests
        run: mvn test

      - name: Verify JARs exist
        run: |
          ls transaction-gateway/target/
          ls ledger-service/target/
          ls analytics-worker/target/

      - name: Build Docker Images
        run: docker compose build